name: movies
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.2
  page_transition: ^2.1.0
  animated_toggle_switch: ^0.8.5
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.4
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  toggle_switch: ^2.3.0
  carousel_slider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
